//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string ipaddress { get; set; }
        public int portnumber { get; set; }
        public int jobscompleted { get; set; }
    }
}
